export const dataA = [
  {
    _id: "GeneF",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene03",
    labelSize: "",
    leftEndPosition: "200",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "gene",
    objectRGBColor: "150,150,100",
    rightEndPosition: "900",
    strand: "reverse",
    tooltip: "this a gene F"
  },
  {
    _id: "GeneE",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene03",
    labelSize: "",
    leftEndPosition: "950",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "gene",
    objectRGBColor: "150,150,100",
    rightEndPosition: "1000",
    strand: "reverse",
    tooltip: "this a gene E"
  },
  {
    _id: "GeneD",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene03",
    labelSize: "",
    leftEndPosition: "150",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "gene",
    objectRGBColor: "150,150,0",
    rightEndPosition: "490",
    strand: "reverse",
    tooltip: "this a gene D"
  },
  {
    _id: "GeneA",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene03",
    labelSize: "",
    leftEndPosition: "+100",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "gene",
    objectRGBColor: "250,0,0",
    rightEndPosition: "600",
    strand: "reverse",
    tooltip: "this a gene A"
  },
  {
    _id: "GeneB",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene03",
    labelSize: "",
    leftEndPosition: "500",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "gene",
    objectRGBColor: "0,250,0",
    rightEndPosition: "800",
    strand: "reverse",
    tooltip: "this a gene B"
  },
  {
    _id: "GeneC",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene03",
    labelSize: "",
    leftEndPosition: "900",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "gene",
    objectRGBColor: "0,0,250",
    rightEndPosition: "1100",
    strand: "reverse",
    tooltip: "this a gene C"
  }
];


export const data = [
  {
    _id: "Gene",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene03",
    labelSize: "",
    leftEndPosition: "100",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "gene",
    objectRGBColor: "0,0,0",
    rightEndPosition: "1400",
    strand: "forward",
    tooltip: "this a gene"
  },
  {
    _id: "Operon",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene03",
    labelSize: "",
    leftEndPosition: "150",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "operon",
    objectRGBColor: "100,100,89",
    rightEndPosition: "1000",
    strand: "forward",
    tooltip: "this a operon"
  },
  {
    _id: "ppGpp",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene01",
    labelSize: "",
    leftEndPosition: "150",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "ppGpp",
    objectRGBColor: "",
    rightEndPosition: "200",
    strand: "reverse",
    tooltip: "this a gene. 1"
  },
  {
    _id: "Promoter",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene002",
    labelSize: "",
    leftEndPosition: "500",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "promoter",
    objectRGBColor: "255,57,243",
    rightEndPosition: "1000",
    strand: "forward",
    tooltip: "<strong>Genome position:</strong><br> 500-1000"
  },
  {
    _id: "Riboswitch",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene002",
    labelSize: "",
    leftEndPosition: "500",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "riboswitch",
    objectRGBColor: "255,57,243",
    rightEndPosition: "1000",
    strand: "forward",
    tooltip: "<strong>Genome position:</strong><br> 500-1000"
  },
  {
    _id: "sRNA",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene002",
    labelSize: "",
    leftEndPosition: "500",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "srna",
    objectRGBColor: "255,57,243",
    rightEndPosition: "1000",
    strand: "forward",
    tooltip: "<strong>Genome position:</strong><br> 500-1000"
  },
  {
    _id: "TF-Binding-sites",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene002",
    labelSize: "",
    leftEndPosition: "500",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "tf_binding_site",
    objectRGBColor: "255,57,243",
    rightEndPosition: "1000",
    strand: "forward",
    tooltip: "<strong>Genome position:</strong><br> 500-1000"
  },
  {
    _id: "Terminator",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene002",
    labelSize: "",
    leftEndPosition: "500",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "terminator",
    objectRGBColor: "255,57,243",
    rightEndPosition: "1000",
    strand: "forward",
    tooltip: "<strong>Genome position:</strong><br> 500-1000"
  },
  {
    _id: "Transcriptional_Atte",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene002",
    labelSize: "",
    leftEndPosition: "500",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "transcriptional_attenuator",
    objectRGBColor: "255,57,243",
    rightEndPosition: "1000",
    strand: "forward",
    tooltip: "<strong>Genome position:</strong><br> 500-1000"
  },
  {
    _id: "Transnational_Attenuator",
    labelFont: "",
    labelRGGColor: "",
    labelName: "Gene002",
    labelSize: "",
    leftEndPosition: "500",
    lineRGBColor: "",
    lineType: "",
    lineWidth: "",
    objectType: "translational_attenuator",
    objectRGBColor: "255,57,243",
    rightEndPosition: "1000",
    strand: "forward",
    tooltip: "<strong>Genome position:</strong><br> 500-1000"
  }
];
